import { AssetCard, AssetSelectionStrip } from '../app/asset-surfaces.jsx';
import { MaterialImportGuide } from '../app/creation-dialogs.jsx';
import { ASSET_BACKSTAGE_COPY } from '../asset-backstage-copy.mjs';
import { ASSET_PAGE_SIZES, normalizeAssetPageSize } from '../asset-pagination.mjs';
import { AssetStateLegend } from '../asset-state-legend.jsx';
import { IconButton } from '../components/IconButton.jsx';
import { PageHeader } from '../components/PageHeader.jsx';
import { PageToolbar } from '../components/PageToolbar.jsx';
import { ASSET_SCOPES, ASSET_SCOPE_LABELS } from '../workbench-route.mjs';
import { Archive, Check, ChevronLeft, ChevronRight, Eye, ImagePlus, Inbox, SlidersHorizontal, Trash2, Upload } from 'lucide-react';

/** 界面批 E（E1.6）从 main.jsx 的 viewRenderers 拆出（行为零变化）。 */
export function AssetsView({ allPageAssetsSelected, assetFilter, assetPage, assetPageSize, assetPreviewFit, assetScope, assetTotal, assets, clearSelection, compareRoundIds, contextMaterialNeeds, copyAsset, deliveries, deliveryIntent, downloadAsset, downloadProjectArchive, importLabel, inputRef, inspectAsset, markAsDeliverable, materialNeedCounts, navigateRoute, pageSelectionBusy, restore, review, routeView, selectedAssetIds, selectedAssets, selectedImportNeed, selectedProject, selectedRound, selectedTask, selectionBusyIds, setAssetFilter, setAssetPage, setAssetPageSize, setAssetPreviewFit, setAssetShared, setPageSelection, setPreviewAssets, setPreviewZoom, setSelectedImportNeed, sharedAssetIds, studio, toggleSelection, totalAssetPages, trash, uploadProgress, uploading, view, visibleAssets }) {
  return <><section className={'asset-stage ' + (selectedAssets.length && routeView === 'assets' ? 'has-selection' : '')}>
    <PageHeader
      kicker={routeView === 'trash' ? '回收站' : (selectedProject?.name || '项目资产')}
      title={routeView === 'trash' ? '回收站' : '资产'}
      description={routeView === 'trash' ? '这里是被回收的图片；还原后回到项目资产。' : ASSET_BACKSTAGE_COPY}
    />
    <PageToolbar label="资产工具"><span className="asset-count">{assetTotal.toString().padStart(2, '0')}</span><span className="asset-count-label">{routeView === 'trash' ? '回收站图片' : '张图片'}</span>{routeView === 'assets' && <div className="asset-scope-control" aria-label="资产范围">{ASSET_SCOPES.filter((scope) => scope !== 'studio').map((scope) => <button type="button" key={scope} className={assetScope === scope ? 'is-active' : ''} disabled={(scope === 'round' && !selectedRound) || (scope === 'task' && !selectedTask) || (scope === 'project' && !selectedProject)} onClick={() => navigateRoute({ assetScope: scope })}>{ASSET_SCOPE_LABELS[scope]}</button>)}</div>}
        {routeView === 'assets' && selectedProject && <button type="button" className="command-button asset-import-button" disabled={uploading} onClick={() => inputRef.current?.click()}><Upload size={16} />{uploading && uploadProgress ? '正在导入 ' + uploadProgress.completed + '/' + uploadProgress.total : importLabel}</button>}
        <div className="asset-filter" aria-label="素材筛选"><SlidersHorizontal size={14} />{[['all', '全部'], ['generated', '生成'], ['import', '导入']].map(([value, label]) => <button type="button" key={value} className={assetFilter === value ? 'is-active' : ''} onClick={() => { setAssetFilter(value); setAssetPage(1); }}>{label}</button>)}</div>
        {routeView === 'assets' && visibleAssets.length > 0 && <button type="button" className="outline-button asset-select-page" disabled={pageSelectionBusy} onClick={() => void setPageSelection(!allPageAssetsSelected)}><Check size={15} />{allPageAssetsSelected ? '取消全选本页' : '全选本页'}</button>}
        <details className="asset-view-options"><summary><SlidersHorizontal size={14} />显示<span className="asset-view-current">{assetPreviewFit === 'adaptive' ? '自适应卡片' : assetPreviewFit === 'cover-top' ? '填满裁切' : '完整显示'}</span></summary><div className="asset-view-panel"><label className="asset-page-size"><span>每页</span><select aria-label="每页资产数量" value={assetPageSize} onChange={(event) => { setAssetPageSize(normalizeAssetPageSize(event.target.value)); setAssetPage(1); }}>{ASSET_PAGE_SIZES.map((size) => <option value={size} key={size}>{size}</option>)}</select><span>张</span></label><div className="asset-view-mode" aria-label="缩略图显示方式"><span>缩略图显示方式</span><button type="button" aria-pressed={assetPreviewFit === 'adaptive'} className={assetPreviewFit === 'adaptive' ? 'is-active' : ''} onClick={() => setAssetPreviewFit('adaptive')}>自适应卡片<span>按原图比例展示</span></button><button type="button" aria-pressed={assetPreviewFit === 'contain'} className={assetPreviewFit === 'contain' ? 'is-active' : ''} onClick={() => setAssetPreviewFit('contain')}>完整显示<span>留白不裁切</span></button><button type="button" aria-pressed={assetPreviewFit === 'cover-top'} className={assetPreviewFit === 'cover-top' ? 'is-active' : ''} onClick={() => setAssetPreviewFit('cover-top')}>填满裁切<span>铺满卡片，优先显示上半部</span></button></div></div></details>
        {routeView === 'assets' && selectedProject && <AssetStateLegend title="状态说明" compact collapsed />}
        {routeView === 'assets' && selectedProject && <button type="button" className="outline-button asset-trash-link" onClick={() => navigateRoute({ view: 'trash', taskId: null, roundId: null, compareRoundIds: [], runId: null, assetScope: 'project' })}><Trash2 size={15} />回收站</button>}
        {routeView === 'trash' && selectedProject && <button type="button" className="outline-button" onClick={() => navigateRoute({ view: 'assets', assetScope: 'project' })}><ImagePlus size={15} />返回素材</button>}
        {selectedAssets.length >= 2 && <IconButton label={'对比选中的 ' + selectedAssets.length + ' 张素材'} onClick={() => { setPreviewZoom(1); setPreviewAssets(selectedAssets); }}><Eye size={16} /></IconButton>}
        <div className="asset-hint">{routeView === 'trash' ? '当前项目回收站' : selectedAssetIds.size ? selectedAssetIds.size + ' 张已选择' : ASSET_SCOPE_LABELS[assetScope] + '资产'}</div>
    </PageToolbar>
    {routeView === 'assets' && selectedProject && <MaterialImportGuide materialNeeds={contextMaterialNeeds} selectedNeed={selectedImportNeed} completedCounts={materialNeedCounts} assetScope={assetScope} selectedRound={selectedRound} onSelectNeed={setSelectedImportNeed} />}
    {routeView === 'assets' && selectedProject && selectedAssets.length > 0 && <AssetSelectionStrip assets={selectedAssets} deliverIntent={deliveryIntent} onRemove={toggleSelection} onClear={() => void clearSelection()} onDownloadArchive={() => downloadProjectArchive(selectedAssets.map((asset) => asset.id))} onDeliver={() => navigateRoute({ view: 'deliveries', taskId: null, roundId: null, compareRoundIds: [], runId: null })} onPreview={(nextAssets) => { setPreviewZoom(1); setPreviewAssets(nextAssets); }} />}
    {visibleAssets.length ? <><div className={'asset-grid is-preview-' + assetPreviewFit}>{visibleAssets.map((asset) => <AssetCard key={asset.id} asset={asset} selected={selectedAssetIds.has(asset.id)} selectionBusy={selectionBusyIds.has(asset.id)} shared={sharedAssetIds.has(asset.id)} previewFit={assetPreviewFit} onReview={review} onToggleSelect={markAsDeliverable} onTrash={trash} onRestore={restore} onInspect={inspectAsset} onDownload={downloadAsset} onCopy={copyAsset} onSetShared={setAssetShared} onPreview={(nextAssets) => { setPreviewZoom(1); setPreviewAssets(nextAssets); }} />)}</div><nav className="asset-pagination" aria-label="资产分页"><button type="button" className="outline-button" disabled={assetPage <= 1} onClick={() => setAssetPage((current) => Math.max(1, current - 1))}><ChevronLeft size={15} />上一页</button><span>第 <b>{assetPage}</b> / {totalAssetPages} 页 · 共 {assetTotal} 张</span><button type="button" className="outline-button" disabled={assetPage >= totalAssetPages} onClick={() => setAssetPage((current) => Math.min(totalAssetPages, current + 1))}>下一页<ChevronRight size={15} /></button></nav></> : <div className="empty-stage asset-empty">{routeView === 'trash' ? <Archive size={30} strokeWidth={1.15} /> : <Inbox size={30} strokeWidth={1.15} />}<p>{routeView === 'trash' ? '当前项目回收站为空' : (assetScope === 'round' && !selectedRound ? '请先从任务里选择批次，再查看本轮结果。' : '当前范围内暂未找到资产。')}</p>{routeView === 'assets' && <button type="button" className="outline-button" onClick={() => inputRef.current?.click()}><Upload size={16} />导入图片</button>}</div>}
  </section></>;
}
