import { createId, nowIso } from '../shared/ids';
import { appendStudioEvent, StudioDatabase, withTransaction } from '../studio/database';
import { executeIdempotent, InvalidCommandError, StudioNotFoundError } from './studio-commands';
import { Delivery, getDelivery } from './deliveries';

type JsonRecord = Record<string, unknown>;
type BatchStatus = 'draft' | 'ready' | 'superseded';

export interface DeliveryBatchMember { deliveryId: string; sequence: number; delivery: JsonRecord; createdAt: string; }
export interface DeliveryBatchVersion { id: string; versionNo: number; predecessorVersionId: string | null; status: BatchStatus; manifest: JsonRecord; createdAt: string; preparedAt: string | null; supersededAt: string | null; members: DeliveryBatchMember[]; }
export interface DeliveryBatch { id: string; projectId: string; name: string; createdAt: string; updatedAt: string; versions: DeliveryBatchVersion[]; }

interface ProjectRow { id: string; studio_id: string; }
interface BatchRow { id: string; project_id: string; name: string; created_at: string; updated_at: string; }
interface VersionRow { id: string; batch_id: string; version_no: number; predecessor_version_id: string | null; status: BatchStatus; manifest_json: string; created_at: string; prepared_at: string | null; superseded_at: string | null; }

function parse(value: string): JsonRecord { try { const result = JSON.parse(value) as unknown; return result && typeof result === 'object' && !Array.isArray(result) ? result as JsonRecord : {}; } catch { return {}; } }
function safe(value: unknown): unknown { if (Array.isArray(value)) return value.map(safe); if (!value || typeof value !== 'object') return value; const result: JsonRecord = {}; for (const [key, item] of Object.entries(value as JsonRecord)) if (!/(api[_-]?key|authorization|secret|token|base[_-]?url|endpoint|password|external.*request|storage.*path|content.*hash)/i.test(key)) result[key] = safe(item); return result; }
function required(value: string, label: string): string { const text = String(value || '').trim(); if (!text) throw new InvalidCommandError(label + ' is required.'); return text; }
function project(db: StudioDatabase, studioId: string, projectId: string): ProjectRow { const row = db.prepare('SELECT id, studio_id FROM projects WHERE id = ? AND studio_id = ?').get(projectId, studioId) as ProjectRow | undefined; if (!row) throw new StudioNotFoundError('Project not found: ' + projectId); return row; }
function batch(db: StudioDatabase, studioId: string, batchId: string): BatchRow { const row = db.prepare('SELECT batch.id, batch.project_id, batch.name, batch.created_at, batch.updated_at FROM delivery_batches batch JOIN projects project ON project.id = batch.project_id WHERE batch.id = ? AND project.studio_id = ?').get(batchId, studioId) as BatchRow | undefined; if (!row) throw new StudioNotFoundError('Delivery batch not found: ' + batchId); return row; }
function latestVersion(db: StudioDatabase, batchId: string): VersionRow | null { return db.prepare('SELECT id, batch_id, version_no, predecessor_version_id, status, manifest_json, created_at, prepared_at, superseded_at FROM delivery_batch_versions WHERE batch_id = ? ORDER BY version_no DESC LIMIT 1').get(batchId) as VersionRow | undefined || null; }
function members(db: StudioDatabase, versionId: string): DeliveryBatchMember[] { const rows = db.prepare('SELECT delivery_id, sequence, delivery_snapshot_json, created_at FROM delivery_batch_version_deliveries WHERE version_id = ? ORDER BY sequence').all(versionId) as Array<{ delivery_id: string; sequence: number; delivery_snapshot_json: string; created_at: string }>; return rows.map((row) => ({ deliveryId: row.delivery_id, sequence: row.sequence, delivery: safe(parse(row.delivery_snapshot_json)) as JsonRecord, createdAt: row.created_at })); }
function publicVersion(db: StudioDatabase, row: VersionRow): DeliveryBatchVersion { return { id: row.id, versionNo: row.version_no, predecessorVersionId: row.predecessor_version_id, status: row.status, manifest: safe(parse(row.manifest_json)) as JsonRecord, createdAt: row.created_at, preparedAt: row.prepared_at, supersededAt: row.superseded_at, members: members(db, row.id) }; }
function publicBatch(db: StudioDatabase, row: BatchRow): DeliveryBatch { const versions = db.prepare('SELECT id, batch_id, version_no, predecessor_version_id, status, manifest_json, created_at, prepared_at, superseded_at FROM delivery_batch_versions WHERE batch_id = ? ORDER BY version_no DESC').all(row.id) as unknown as VersionRow[]; return { id: row.id, projectId: row.project_id, name: row.name, createdAt: row.created_at, updatedAt: row.updated_at, versions: versions.map((version) => publicVersion(db, version)) }; }
function readyDeliverySnapshot(db: StudioDatabase, projectId: string, deliveryId: string): JsonRecord { const delivery = getDelivery(db, deliveryId) as Delivery; if (delivery.projectId !== projectId) throw new InvalidCommandError('Delivery does not belong to the selected project.'); if (delivery.status !== 'ready' && delivery.status !== 'exported') throw new InvalidCommandError('A batch can only include prepared or exported deliveries.'); return safe({ id: delivery.id, name: delivery.name, status: delivery.status, manifest: delivery.manifest, items: delivery.items || [] }) as JsonRecord; }
function insertVersion(db: StudioDatabase, project: ProjectRow, batchRow: BatchRow, versionNo: number, predecessorVersionId: string | null, deliveryIds: string[], timestamp: string): DeliveryBatchVersion { const uniqueIds = [...new Set(deliveryIds)]; if (!uniqueIds.length) throw new InvalidCommandError('A delivery batch version requires at least one prepared delivery.'); const versionId = createId('delivery_batch_version'); const snapshots = uniqueIds.map((id) => readyDeliverySnapshot(db, project.id, id)); const manifest = { deliveryIds: uniqueIds, deliveryCount: snapshots.length, frozenAt: timestamp }; db.prepare('INSERT INTO delivery_batch_versions (id, batch_id, version_no, predecessor_version_id, status, manifest_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)').run(versionId, batchRow.id, versionNo, predecessorVersionId, 'draft', JSON.stringify(manifest), timestamp); for (const [index, snapshot] of snapshots.entries()) db.prepare('INSERT INTO delivery_batch_version_deliveries (version_id, delivery_id, sequence, delivery_snapshot_json, created_at) VALUES (?, ?, ?, ?, ?)').run(versionId, uniqueIds[index], index + 1, JSON.stringify(snapshot), timestamp); return publicVersion(db, db.prepare('SELECT id, batch_id, version_no, predecessor_version_id, status, manifest_json, created_at, prepared_at, superseded_at FROM delivery_batch_versions WHERE id = ?').get(versionId) as unknown as VersionRow); }

export function listDeliveryBatches(db: StudioDatabase, studioId: string, projectId: string): DeliveryBatch[] { project(db, studioId, projectId); return (db.prepare('SELECT id, project_id, name, created_at, updated_at FROM delivery_batches WHERE project_id = ? ORDER BY updated_at DESC, id DESC').all(projectId) as unknown as BatchRow[]).map((row) => publicBatch(db, row)); }
export function getDeliveryBatch(db: StudioDatabase, studioId: string, batchId: string): DeliveryBatch { return publicBatch(db, batch(db, studioId, batchId)); }
export function createDeliveryBatch(db: StudioDatabase, input: { studioId: string; projectId: string; name: string; deliveryIds: string[]; idempotencyKey: string }): DeliveryBatch { const receipt = executeIdempotent(db, input.idempotencyKey, 'delivery_batches.create', () => withTransaction(db, () => { const owner = project(db, input.studioId, input.projectId); const timestamp = nowIso(); const row: BatchRow = { id: createId('delivery_batch'), project_id: owner.id, name: required(input.name, 'Delivery batch name'), created_at: timestamp, updated_at: timestamp }; db.prepare('INSERT INTO delivery_batches (id, project_id, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?)').run(row.id, row.project_id, row.name, row.created_at, row.updated_at); const version = insertVersion(db, owner, row, 1, null, input.deliveryIds, timestamp); appendStudioEvent(db, { studioId: owner.studio_id, entityType: 'delivery_batch', entityId: row.id, eventType: 'delivery_batch.version_drafted', payload: { versionId: version.id, versionNo: 1, deliveryCount: version.members.length } }); return publicBatch(db, row); }), input); return receipt.value; }
export function reviseDeliveryBatch(db: StudioDatabase, input: { studioId: string; batchId: string; deliveryIds: string[]; idempotencyKey: string }): DeliveryBatch { const receipt = executeIdempotent(db, input.idempotencyKey, 'delivery_batches.revise', () => withTransaction(db, () => { const row = batch(db, input.studioId, input.batchId); const owner = project(db, input.studioId, row.project_id); const predecessor = latestVersion(db, row.id); if (!predecessor) throw new StudioNotFoundError('Delivery batch has no versions: ' + row.id); const timestamp = nowIso(); if (predecessor.status === 'draft') db.prepare('UPDATE delivery_batch_versions SET status = ?, superseded_at = ? WHERE id = ?').run('superseded', timestamp, predecessor.id); const version = insertVersion(db, owner, row, predecessor.version_no + 1, predecessor.id, input.deliveryIds, timestamp); db.prepare('UPDATE delivery_batches SET updated_at = ? WHERE id = ?').run(timestamp, row.id); appendStudioEvent(db, { studioId: owner.studio_id, entityType: 'delivery_batch', entityId: row.id, eventType: 'delivery_batch.version_drafted', payload: { versionId: version.id, versionNo: version.versionNo, predecessorVersionId: predecessor.id, deliveryCount: version.members.length } }); return publicBatch(db, { ...row, updated_at: timestamp }); }), input); return receipt.value; }
export function prepareDeliveryBatchVersion(db: StudioDatabase, input: { studioId: string; versionId: string; idempotencyKey: string }): DeliveryBatch { const receipt = executeIdempotent(db, input.idempotencyKey, 'delivery_batches.ready', () => withTransaction(db, () => { const version = db.prepare('SELECT version.id, version.batch_id, version.version_no, version.predecessor_version_id, version.status, version.manifest_json, version.created_at, version.prepared_at, version.superseded_at FROM delivery_batch_versions version JOIN delivery_batches batch ON batch.id = version.batch_id JOIN projects project ON project.id = batch.project_id WHERE version.id = ? AND project.studio_id = ?').get(input.versionId, input.studioId) as VersionRow | undefined; if (!version) throw new StudioNotFoundError('Delivery batch version not found: ' + input.versionId); if (version.status !== 'draft') throw new InvalidCommandError('Only a draft batch version can be prepared.'); const row = batch(db, input.studioId, version.batch_id); const timestamp = nowIso(); db.prepare('UPDATE delivery_batch_versions SET status = ?, prepared_at = ? WHERE id = ?').run('ready', timestamp, version.id); db.prepare('UPDATE delivery_batches SET updated_at = ? WHERE id = ?').run(timestamp, row.id); appendStudioEvent(db, { studioId: input.studioId, entityType: 'delivery_batch', entityId: row.id, eventType: 'delivery_batch.version_ready', payload: { versionId: version.id, versionNo: version.version_no } }); return publicBatch(db, { ...row, updated_at: timestamp }); }), input); return receipt.value; }
